export type Task = {
  source_url?: string | null;
  source_link_kind?: string;
  local_completed: boolean;
  local_completed_at: string | null;
  completion_origin: string | null;
  state_revision: number;
  submission_state: string | null;
  id: number;
  course_id: number;
  title: string;
  task_type: string;
  due_at: string | null;
  assigned_date_local: string | null;
  due_date_local: string | null;
  deadline_precision: string | null;
  deadline_timezone: string | null;
  source_deadline_text: string | null;
  points_possible: number | null;
  status: string;
  ignored_at: string | null;
};
export type Course = {
  id: number;
  course_code: string;
  name: string;
  term: string | null;
  lifecycle_state: "ACTIVE" | "ARCHIVED";
  archived_at: string | null;
  term_id: string | null;
  term_name: string | null;
  term_start_at: string | null;
  term_end_at: string | null;
  term_sort_key: string;
  display_course_code: string | null;
  display_name: string | null;
  section: string | null;
  commute_minutes: number;
};
export type CourseTerm = {
  term_id: string;
  display_name: string;
  active_course_count: number;
  archived_course_count: number;
  is_default: boolean;
};
export type Change = {
  id: number;
  source_item_id: number;
  change_type: string;
  detected_at: string;
  importance: string;
  summary: string;
  ai_summary: string | null;
  read_at: string | null;
  category: string;
  change_field: string | null;
  course_code: string | null;
  title: string | null;
  primary_text: string | null;
  event_label: string | null;
  has_meaningful_diff: boolean;
};
export type FileRecord = {
  id: number;
  course_id: number;
  course_code: string;
  course_name: string;
  source_url: string;
  original_filename: string;
  local_path: string;
  category: string;
  source_detected_type: string | null;
  user_override_type: string | null;
  effective_type: string;
  size_bytes: number;
  mime_type: string | null;
  version_number: number;
  downloaded_at: string;
  integrity_status: string;
  validation_error: string | null;
  export_name: string | null;
  export_path: string | null;
  export_status: string;
  export_error: string | null;
  source_deleted: boolean;
};
export type PlanBlock = {
  id: number;
  task_id: number;
  task_title: string;
  start_at: string;
  end_at: string;
  objective: string;
  status: string;
};
export type CanvasStatus = {
  connection_state?: string;
  effective_method?: "oauth" | "pat" | "browser_session" | null;
  preferred_method?: "oauth" | "pat" | "browser_session";
  backup_ready?: boolean;
  credentials?: Record<string, { present: boolean; state: string; generation: number; last_verified_at: string | null; expires_at?: string | null; expiration_source?: string; origin?: string }>;
  fallback?: { from: string; to: string; reason_code: string } | null;
  configured: boolean;
  auth_mode: "oauth" | "pat" | "browser_session" | null;
  credential_state: string;
  source_health: string;
  verified: boolean;
  verified_at: string | null;
  account_id: string | null;
  account_display_name: string | null;
  expires_at: string | null;
  days_remaining: number | null;
  expiration_state: string;
  expiration_source: string | null;
};
export type AuthProfile = {
  credential_id: string;
  auth_type: string;
  auth_mode: "pat" | "browser_session" | null;
  username: string | null;
  display_name: string | null;
  probe_url: string;
  metadata_json: { base_url?: string; auth_mode?: "pat" | "browser_session" };
  state: string;
  last_verified_at: string | null;
  last_failure_at: string | null;
  last_error_code: string | null;
};
export type CourseSource = {
  id: number;
  course_id: number;
  name: string;
  source_type: string;
  external_id: string | null;
  url: string | null;
  enabled: boolean;
  state: string;
  last_success_at: string | null;
  last_error: string | null;
  health_summary?: string | null;
  health_diagnostics?: { resource: string; code: string; http_status: number | null; historical?: boolean }[];
};
export type PendingResource = {
  id: number;
  course_id: number;
  source_name: string;
  url: string;
  title: string;
  item_type: string;
  credential_id: string | null;
  state: string;
  last_error_code: string | null;
};
export type ChangeDetail = {
  id: number;
  course: { id: number; course_code: string; name: string } | null;
  title: string | null;
  change_type: string;
  detected_at: string;
  source_type: string | null;
  source_url: string | null;
  importance: string;
  requires_action: boolean;
  summary: string;
  ai_summary: string | null;
  primary_text: string;
  event_label: string;
  has_meaningful_diff: boolean;
  read_at: string | null;
  category: string;
  change_field: string | null;
  old: {
    id: number;
    captured_at: string;
    structured: Record<string, unknown>;
    normalized_text: string;
  } | null;
  new: {
    id: number;
    captured_at: string;
    structured: Record<string, unknown>;
    normalized_text: string;
  } | null;
  new_file: {
    filename: string;
    size_bytes: number;
    integrity_status: string;
  } | null;
  related_task: Task | null;
  internal_metadata: Record<string, unknown>;
};
export type TodayWork = {
  provider_facts?: { provider: string; source_item_id: number; due_at: string | null; late_due_at: string | null; submission_state: string | null; direct_assignment_url: string | null }[];
  state_revision?: number;
  local_completed?: boolean;
  submission_state?: string | null;
  source_url?: string | null;
  source_link_kind?: "assignment" | "course_page" | "unavailable";
  task_id: number;
  course_id: number;
  course_code: string;
  title: string;
  deadline: string | null;
  deadline_precision: string | null;
  due_date_local?: string | null;
  progress: number;
  effective_total_minutes: number;
  remaining_minutes: number;
  estimate_source: "observed_ratio" | "ai_calibrated" | "ai" | "fallback";
  estimate_confidence: number;
  analysis_status: "PENDING" | "READY" | "FAILED";
  priority_score: number;
  priority_bucket: "Low" | "Medium" | "High" | "Critical";
  today_reason: string;
  slack_minutes: number | null;
  slack_bucket: string;
  tracked_minutes: number;
  manual_adjustment_minutes: number;
  effective_used_minutes: number;
  is_working: boolean;
  active_started_at: string | null;
  active_elapsed_seconds: number;
};
export type TodayAttention = {
  ai_reviewed?: boolean;
  review_reason?: string | null;
  reviewed_at?: string | null;
  change_id: number;
  course_id: number;
  course_code: string;
  summary: string;
  severity: string;
  importance: number;
  requires_action: boolean;
  recommended_action: string | null;
  affected_task_ids: number[];
  detected_at: string;
  analysis_status: "PENDING" | "READY" | "FAILED";
};
export type TodayData = {
  date: string;
  timezone: string;
  work: TodayWork[];
  completed?: TodayWork[];
  attention: TodayAttention[];
  capacity_minutes: number | null;
  capacity_source: "calendar" | "availability" | "fallback";
};
export type WorkSession = {
  id: number;
  task_id: number;
  started_at: string;
  ended_at: string | null;
  duration_seconds: number | null;
  source: string;
};
export type WorkSummary = {
  task_id: number;
  tracked_minutes: number;
  manual_adjustment_minutes: number;
  effective_used_minutes: number;
  active_session_id: number | null;
  active_started_at: string | null;
  active_elapsed_seconds: number;
  sessions: WorkSession[];
  switched_from_task_id: number | null;
};
export type CalendarEvent = {
  id: number;
  calendar_id: string;
  external_id: string | null;
  source: "manual" | "google" | "ics";
  summary: string;
  description: string;
  location: string | null;
  start_at: string;
  end_at: string;
  start_date: string | null;
  end_date: string | null;
  all_day: boolean;
  timezone: string;
  recurrence_rule: string | null;
  recurring_event_id: string | null;
  original_start_at: string | null;
  status: string;
  transparency: string;
  read_only: boolean;
  event_type: "class" | "busy" | "personal" | "study" | "other";
  course_id: number | null;
  import_source_id: number | null;
};
export type AvailabilityRule = {
  id?: number;
  weekday: number;
  start_local_time: string;
  end_local_time: string;
  enabled: boolean;
};
export type AvailabilityOverride = {
  id?: number;
  date: string;
  available_intervals: { start: string; end: string }[];
};
export type SourceConnection = {
  id: number;
  source_type: "canvas" | "website" | "gradescope" | "prairielearn";
  name: string;
  base_url: string | null;
  course_id: number | null;
  credential_id: string | null;
  config_json: Record<string, unknown>;
  state: string;
};
export type AIProbeSettings = {
  provider: string;
  providers: { id: string; label: string; base_url: string; requires_key: boolean }[];
  needs_provider_selection: boolean;
  base_url: string;
  model_id: string;
  credential_loaded: boolean;
  connected_to_live_ai: boolean;
  calendar_chat_ready: boolean;
  chat_ready: boolean;
};
export type GoogleCalendarStatus = {
  configured: boolean;
  state: string;
  connected_account: string | null;
  scopes: string[];
  last_successful_sync: string | null;
  last_error: string | null;
  calendars: {
    id: string;
    summary: string;
    primary: boolean;
    selected: boolean;
    access_role: string | null;
    timezone: string | null;
    state: string;
    last_sync_at: string | null;
  }[];
};
export type ICSImportSource = {
  id: number;
  original_filename: string;
  calendar_name: string | null;
  calendar_timezone: string | null;
  event_count: number;
  recurring_series_count: number;
  imported_at: string;
  last_reimported_at: string | null;
  file_sha256: string;
  state: string;
  read_only: true;
};
export type ICSPreview = {
  status: "ready";
  events_found: number;
  warnings: string[];
  original_filename: string;
  calendar_name: string | null;
  calendar_timezone: string | null;
  timezone_confirmation_required: boolean;
  event_count: number;
  recurring_series_count: number;
  reconciliation: {
    new: number;
    updated: number;
    removed: number;
    unchanged: number;
  };
  no_op: boolean;
  file_sha256: string;
};
export type AppNotification = {
  id: number;
  level: "important" | "critical";
  title: string;
  body: string;
  status: string;
  sent_at: string | null;
};
